added modal and close/open btn
BohdanRecruiter/group-project-js pull request #7
Opened 2022-05-07 15:23 UTC by mrnobody3

Провір, будь-ласка, як дизайн, та функціонал стартовий додав

2022-05-07 15:44 UTC, AnthonyUPTN commented on src/js/movieModal.js
> +  document.body.style.overflow = 'scroll';
добавить ещё снятие слушателя
document.removeEventListener('keydown', onCloseByEsc);
что б каждое нажатие по клавиатуре прекращало слушаться

2022-05-07 15:44 UTC, AnthonyUPTN commented on src/partials/movieModal.html
> +          <p class="film__info">Vote / Votes</p>
вместо тега <p> - <span>
тег <p> - всё таки абзац, а спан - всего лишь не семантическая обвёртка

для того что бы всё стало колонками - width: 50%

2022-05-07 15:44 UTC, AnthonyUPTN commented on src/partials/movieModal.html
> +          <p class="film__info">Vote / Votes</p>
стили не смотрел

2022-05-07 15:46 UTC, AnthonyUPTN commented on src/js/movieModal.js
> +  if (e.target === backdropRef) return onCloseMovieModal();
if (e.target === backdropRef)  {
onCloseMovieModal(); }

2022-05-07 16:15 UTC, BohdanRecruiter requested changes

2022-05-07 16:15 UTC, BohdanRecruiter commented on src/partials/movieModal.html
> +          <p class="film__info">Vote / Votes</p>
Спан швидше для стилізації контенту в абзаці. Так що p цілком підходить

2022-05-07 16:15 UTC, BohdanRecruiter commented on src/sass/_movieModal.scss
> +  z-index: 2;
Можливо, варто зробити модалці більший z-index (999)

2022-05-07 17:14 UTC, mrnobody3 commented on src/js/movieModal.js
> +  document.body.style.overflow = 'scroll';
+

2022-05-07 17:14 UTC, mrnobody3 commented on src/partials/movieModal.html
> +          <p class="film__info">Vote / Votes</p>
поставил тег р вмсесто спан

2022-05-07 17:14 UTC, mrnobody3 commented on src/js/movieModal.js
> +  if (e.target === backdropRef) return onCloseMovieModal();
+

2022-05-07 17:14 UTC, mrnobody3 commented on src/sass/_movieModal.scss
> +  z-index: 2;
+

2022-05-07 17:17 UTC, AnthonyUPTN commented on src/partials/movieModal.html
> +          <p class="film__info">Vote / Votes</p>
так это же не абзац, а список. и в стилизации текста лучше использовать спан. ну р, так р. ок)

2022-05-07 18:03 UTC, AnthonyUPTN approved these changes

2022-05-07 18:06 UTC, AnthonyUPTN approved these changes

2022-05-07 18:19 UTC, AnthonyUPTN approved these changes

2022-05-08 13:59 UTC, BohdanRecruiter commented on src/js/movieModal.js
> +btnCloseModalRef.addEventListener('click', onCloseMovieModal);
Зроби, будь ласка, так, щоб btnCloseModalRef мав слухача тільки при відкритій модалці)

2022-05-08 14:25 UTC, mrnobody3 commented on src/js/movieModal.js
> +btnCloseModalRef.addEventListener('click', onCloseMovieModal);
+

2022-05-08 21:31 UTC, BohdanRecruiter approved these changes

2022-05-08 21:31 UTC, merged